language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-zf5' ]; then cd .. && eval "mv $currentfolder generator-zf5" && cd generator-zf5; fi

